#ifndef __AS__TYPE_
#define __AS__TYPE_
typedef struct {
	unsigned char bit0  : 1;
	unsigned char bit1  : 1;
	unsigned char bit2  : 1;
	unsigned char bit3  : 1;
	unsigned char bit4  : 1;
	unsigned char bit5  : 1;
	unsigned char bit6  : 1;
	unsigned char bit7  : 1;
} _1byte_bit_field_;

typedef struct {
	unsigned short bit0  : 1;
	unsigned short bit1  : 1;
	unsigned short bit2  : 1;
	unsigned short bit3  : 1;
	unsigned short bit4  : 1;
	unsigned short bit5  : 1;
	unsigned short bit6  : 1;
	unsigned short bit7  : 1;
	unsigned short bit8  : 1;
	unsigned short bit9  : 1;
	unsigned short bit10 : 1;
	unsigned short bit11 : 1;
	unsigned short bit12 : 1;
	unsigned short bit13 : 1;
	unsigned short bit14 : 1;
	unsigned short bit15 : 1;
} _2byte_bit_field_;

typedef struct {
	unsigned long bit0  : 1;
	unsigned long bit1  : 1;
	unsigned long bit2  : 1;
	unsigned long bit3  : 1;
	unsigned long bit4  : 1;
	unsigned long bit5  : 1;
	unsigned long bit6  : 1;
	unsigned long bit7  : 1;
	unsigned long bit8  : 1;
	unsigned long bit9  : 1;
	unsigned long bit10 : 1;
	unsigned long bit11 : 1;
	unsigned long bit12 : 1;
	unsigned long bit13 : 1;
	unsigned long bit14 : 1;
	unsigned long bit15 : 1;
	unsigned long bit16 : 1;
	unsigned long bit17 : 1;
	unsigned long bit18 : 1;
	unsigned long bit19 : 1;
	unsigned long bit20 : 1;
	unsigned long bit21 : 1;
	unsigned long bit22 : 1;
	unsigned long bit23 : 1;
	unsigned long bit24 : 1;
	unsigned long bit25 : 1;
	unsigned long bit26 : 1;
	unsigned long bit27 : 1;
	unsigned long bit28 : 1;
	unsigned long bit29 : 1;
	unsigned long bit30 : 1;
	unsigned long bit31 : 1;
} _4byte_bit_field_;
#endif

struct TON
{	plctime PT;
	plctime ET;
	plctime StartTime;
	unsigned long Restart;
	plcbit IN;
	plcbit Q;
	plcbit M;
};
_BUR_PUBLIC void TON(struct TON* inst);
struct FMHCounter
{	float Counter;
	unsigned short Tik;
	struct TON T;
	plcbit Run;
	plcbit Reset;
};
_BUR_PUBLIC void FMHCounter(struct FMHCounter* inst);
struct FMotor
{	unsigned short Status;
	float MotoHours;
	struct FMHCounter MH;
	struct TON T;
	plcbit Start;
	plcbit Stop;
	plcbit RunDI;
	plcbit Reset;
	plcbit Block;
	plcbit Imitation;
	plcbit ResetMH;
	plcbit StartDO;
	plcbit StopDO;
	plcbit Started_old;
	plcbit Started;
	plcbit Stopped_old;
	plcbit Stopped;
	plcbit Timeout;
};
_BUR_PUBLIC void FMotor(struct FMotor* inst);
struct FDO
{	plcbit In;
	plcbit Inv;
	plcbit Mask;
	plcbit MaskEn;
	plcbit Out;
};
_BUR_PUBLIC void FDO(struct FDO* inst);
struct FDI
{	plcbit In;
	plcbit Inv;
	plcbit Mask;
	plcbit MaskEn;
	plcbit Out;
};
_BUR_PUBLIC void FDI(struct FDI* inst);
struct FAO
{	float HiHiLimit;
	float HiLimit;
	float LoLimit;
	float LoLoLimit;
	float Replace_Value;
	unsigned short r0;
	float LoScale;
	float HiScale;
	float Value;
	signed short RAW;
	signed short RAW1;
	float Current;
	unsigned short r1;
	signed short HiHiLimitPAZ;
	float Scale;
	plcbit HiHiEnabled;
	plcbit HiEnabled;
	plcbit LoEnabled;
	plcbit LoLoEnabled;
	plcbit ImitationEn;
	plcbit CurrentOK;
	plcbit CannelOK;
	plcbit Diff;
	plcbit Safe;
	plcbit HiHiAlarm;
	plcbit HiAlarm;
	plcbit LoAlarm;
	plcbit LoLoAlarm;
	plcbit Invalid;
};
_BUR_PUBLIC void FAO(struct FAO* inst);
struct FAI
{	signed short RAW;
	unsigned char ChannelType;
	float HiScale;
	float LoScale;
	float HiHiLimit;
	float HiLimit;
	float LoLimit;
	float LoLoLimit;
	float Replace_Value;
	float Hyst;
	unsigned char RegCmd;
	float MbValue;
	float Value;
	float Current;
	unsigned char Color;
	unsigned char RegStatus;
	float Scale;
	plcbit ChannelUnderflow;
	plcbit ChannelOverflow;
	plcbit ImitationEn;
	plcbit HiHiEnabled;
	plcbit HiEnabled;
	plcbit LoEnabled;
	plcbit LoLoEnabled;
	plcbit Invalid;
	plcbit HiHiAlarm;
	plcbit HiAlarm;
	plcbit LoAlarm;
	plcbit LoLoAlarm;
};
_BUR_PUBLIC void FAI(struct FAI* inst);
_BUR_LOCAL unsigned char def_AI_MC;
_BUR_LOCAL unsigned char def_AI_WC;
_BUR_LOCAL unsigned char def_AO_MC;
_BUR_LOCAL unsigned char def_AO_WC;
_BUR_LOCAL unsigned char def_DI_MC;
_BUR_LOCAL unsigned char def_DI_WC;
_BUR_LOCAL unsigned char def_DO_MC;
_BUR_LOCAL unsigned char def_DO_WC;
_BUR_LOCAL_RETAIN struct FAI AI[1][4];
_BUR_LOCAL_RETAIN struct FAO AO[1][2];
_BUR_LOCAL_RETAIN struct FDI DI[4][16];
_BUR_LOCAL_RETAIN struct FDO DO_[3][16];
_BUR_LOCAL unsigned char i;
_BUR_LOCAL unsigned char j;
_BUR_LOCAL_RETAIN struct FMotor KM[56];
